### ISSUE TITLE
CPU fallback?

### ISSUE THREAD

**Issue by blizzz** [fangfufu/Linux-Fake-Background-Webcam#1]
> Note that if you don't manage to set up Nvidia Container Toolkit, Tensorflow will fall back to CPU. This is in fact how I run mine - my GPU is too old for the current version of Tensorflow.

But this still requires you to have Nvidia hardware? With my Intel chipset I get "Error response from daemon: could not select device driver "" with capabilities: [[gpu]]" when starting the bodypix container.

**Comment by fangfufu** [comment]
It doesn't require you to have Nvidia hardware, no. It should still run fine. If it doesn't, remove all references to GPU in the Dockerfile.
