### ISSUE TITLE
Apparent memory leak from app.js

### ISSUE THREAD

**Issue by luxaritas** [fangfufu/Linux-Fake-Background-Webcam#100]
While fake.py is running, the memory usage of `node app.js` steadily rises ~10MB/sec.

I currently have this package installed on Manjaro 21.0.5 via fake-background-webcam-git (r142.a26ff20-1). Happy to debug further given guidance

**Comment by luxaritas** [comment]
Particularly bizarre: Tried inspecting the node process, grabbing a heap dump, etc. It only reports ~25MB used. Currently running node v14.16.0

**Comment by fangfufu** [comment]
Try node v14.16 LTS?

**Comment by luxaritas** [comment]
That's what I'm on :) (I was unknowingly on v10 before - yikes! - but upgrading didn't help)

**Comment by luxaritas** [comment]
Ran `tf.memory()` every few seconds, and there isn't an increase in allocated tensors, so I'm at a bit of a loss for _where_ the built up memory is. Is it possible that there's native code used by tfjs that's not getting tracked by the profiler and not resulting in an increase is tracked tensors which has a memory leak? Is it possible that it's related to https://github.com/tensorflow/tfjs/issues/3319?

**Comment by RadekDvorak** [comment]
Hi,

I have git-bisected the bodypix docker image to the first commit that suffers from the memory leak: a26ff20663b7d0165c62f49d4b7d73aaaf533b18. I hope it helps.

**Comment by fangfufu** [comment]
I reverted the last commit.

**Comment by fangfufu** [comment]
Please checkout the latest commit. I got rid off Bodypix. Node.js is no longer required.

**Comment by RadekDvorak** [comment]
Thank you. I have tried 27cc9f5b364027bccf011c5600a3ba581c75a8d0. It works nice. There seems to be no visible CPU usage difference if I sum those former two processes :+1:

There is a visual difference though. Bodypix based solution blurred or smoothed the gradient between the face and the background. As both solutions make part of my chair appear behind my head from time to time, I admit that flickering square blocks are more distracting in the latest version. Not complaining - just FYI

**Comment by fangfufu** [comment]
How about in terms of FPS? 

You can also do thresholding and blurring in the new classifier, but the new classifier returns a mask with transparency anyway, so I decided to just leave it as it is.

Feel free to suggest a patch.

**Comment by RadekDvorak** [comment]
My webcam runs 1280x720 with 15 FPS. There is no visual difference in terms of FPS.

Ad patch: this AI/ML stuff wildly out of my field of expertise. Honestly, I can hardly understand your suggestion.

**Comment by fangfufu** [comment]
It made a huge difference for me. My laptop was doing about 10-14 FPS, now with the new patch, it is doing about 20-24 FPS.
