### ISSUE TITLE
Thank you for your code 

### ISSUE THREAD

**Issue by MaximusMutschler** [fangfufu/Linux-Fake-Background-Webcam#101]
Dear fangfufu,
I just wanted to leave a few words of thanks. 
Building on your (and some others) repository, I implemented a webcam that applies artistic neural style transfer:
(https://github.com/MaximusMutschler/Virtual-Neural-Style-Transfer-Webcam-for-Linux).
Feel free to incorporate some of my implementations back into your project.
You might be interested in:
- A docker container that already contains akvcam.
- Using pytorch models optimized with tensorrt to achieve about 25 FPS on HD
best,
Maximus

Translated with www.DeepL.com/Translator (free version)

**Comment by fangfufu** [comment]
I am glad that you find this useful. :)

**Comment by fangfufu** [comment]
Please checkout the latest commit. I got rid off Bodypix. Node.js is no longer required.
