### ISSUE TITLE
A Tensorflow version issue?

### ISSUE THREAD

**Issue by wwang** [fangfufu/Linux-Fake-Background-Webcam#102]
HI Fufu,

First of all, thank you so much for making this package for Linux users.

I tried to install this package on a new Linux box today and was hit by the following error 
> TypeError: forwardFunc is not a function

Googling this error suggests that this is caused by version mismatch between tfjs and tfjs-core. I checked their versions in my system, the tfjs-core was 3.7.0, and tfjs/tfjs-node were 1.7.4. 

It seems that bodypix 2.2.0 now depends on tfjs-core 3.6.0+, causing the newest tfjs-core 3.7.0 (released a day ago?) being pulled.

I fixed this version issue by changing the version of tjfs-node in package.json to 3.7.0. Nonetheless, I have never coded in node.js, so I am not sure if this is a correct fix. I think you probably want to know this version issue and probably have a better solution.

Also, I am using Debian Bullseye (11.0). 

Best

**Comment by fangfufu** [comment]
Okay fixed version number. The version number was downgraded because of this:
https://github.com/fangfufu/Linux-Fake-Background-Webcam/issues/100

**Comment by wwang** [comment]
Oh my... That is indeed leaking like a sieve... 

In that case, it is probably better to lock the versions to 2.0.x and 1.7.x

I tested the following configuration, seems to work for now
```
{
    "name": "bodypix",
    "version": "0.0.1",
    "dependencies": {
        "@tensorflow-models/body-pix": "~2.0.5",
        "@tensorflow/tfjs-node": "~1.7.4",
        "@tensorflow/tfjs-node-gpu": "~1.7.4"
    }
}
```

**Comment by fangfufu** [comment]
Done. :)

**Comment by wwang** [comment]
Thank you! I will (try to) close this one.

**Comment by fangfufu** [comment]
Please checkout the latest commit. I got rid off Bodypix. Node.js is no longer required.

**Comment by wwang** [comment]
This is new version is much better! Thank you!
