### ISSUE TITLE
CTRL+C doesn't actually reload image

### ISSUE THREAD

**Issue by brandoningli** [fangfufu/Linux-Fake-Background-Webcam#112]
Pressing CTRL+C doesn't actually reload the background image. A full restart of the script is required to do so.

How I'm changing the background is by updating a symbolic link in the image folder for background.jpg.

Command to invoke fake.py: `python3 /path/to/fake.py -w /dev/videox -v /dev/videoy -i /path/to/imagesfolder --no-foreground`

Pop!_OS (Ubuntu) 20.04
Kernel 5.11.0-7614-generic
Project just pulled before submitting this issue.
Python 3.8.5
v4l2loopback from latest git source
Pip Package versions:
```
numpy 1.20,3
opencv-python 4.5.2.54
requests 2.23.0
requests-unixsocket 0.2.0
pyfakewebcam 0.1.0
mediapipe 0.8.5
urllib3 1.25.8
idna 2.8
certifi 2019.11.28
chardet 3.0.4
six 1.15.0
opencv-contrib-python 4.5.2.54
absl-py 0.11.0
wheel 0.36.2
protobuf 3.14.0
attrs 20.3.0
```

**Comment by fangfufu** [comment]
Fixed in 1a11daf5a20be737599f5d80f25def5cca8eb5ca
