### ISSUE TITLE
fakecam error

### ISSUE THREAD

**Issue by bionan** [fangfufu/Linux-Fake-Background-Webcam#12]
Hi,
When using DOCKER with default docker-compose yaml file, I get this message:

> for linux-fake-background-webcam-master_fakecam_1  Cannot start service fakecam: error gathering device information while adding custom device "/dev/video2": no such file or directory

My computer is a Lenovo machine with 1 camera BUT 2 /dev/video: /dev/video0 (real camera) and
/dev/video1 (metadata camera)

Tx for any help.

**Comment by jeremysule** [comment]
Make sure you load the kernel module as described here https://github.com/fangfufu/Linux-Fake-Background-Webcam#prerequisite

**Comment by fangfufu** [comment]
You have to edit the docker-compose.yml and change ``/dev/video2`` to ``/dev/video1``. The instruction is written in ``DOCKER.md``.
