### ISSUE TITLE
Worse filtering with mediapipe

### ISSUE THREAD

**Issue by hp-pepster** [fangfufu/Linux-Fake-Background-Webcam#132]
Hi,

thanks for this repo. I used it a lot in the last couple of weeks.

With your switch to mediapipe, my performance exploded to usable 20-30 fps. Unfortunately, the filtering is way worse compared to tf and bodypix. E.g. hair, microphone etc. is flickering, background sometimes shines through. Are there any settings for mediapipe I could change to improve the filtering?

One side note: Changing the cpu governor from powersave to performance increases my fps a lot. If you are interested I could provide more info about that.

**Comment by fangfufu** [comment]
Please try out this and let me know what you think:
https://github.com/fangfufu/Linux-Fake-Background-Webcam/pull/131

**Comment by hp-pepster** [comment]
Thanks for the hint. The flickering is gone, albeit I'm looking a little bit like a ghost as parts of my head are missing. But overall I would say it's a way better experience. The default value seems sane, 5 is a little bit too slow and 25 tends to flicker a little bit.

**Comment by fangfufu** [comment]
I am quite happy with the default set up I have right now, which is why I haven't merged it in yet. I want to do a bit more testing. I am not sure if I actually experience what you just described. If you don't mind, some pictures would be helpful.

**Comment by hp-pepster** [comment]
Do you mean with your master branch or with PR #131 ? I made a little video with the PR and background_mask_update_speed set to 100 and one with your master. Is it ok if I sent them to you by mail (from your profile)?

**Comment by fangfufu** [comment]
Yeh, both really, I just want to see a comparison. For me this has never been an issue. I don't like the thresholding in the incoming PR.

**Comment by hp-pepster** [comment]
I sent you the videos. Maybe it's light-related, but with daylight it seems to be better. With worse light parts of my face are sometimes completely flickering. Maybe the spooky effect leads to shorter online meetings :-)

**Comment by tommyalatalo** [comment]
I have the same problem, just installed from AUR, the background is flickering around the edges of my silhouette a lot, and sometimes I flicker completely behind it. It's quite unusable in this state, very distracting.

**Comment by fangfufu** [comment]
@hp-pepster , I am not sure if I received your email, what was the title of the email?

**Comment by hp-pepster** [comment]
@fangfufu Linux-Fake-Background-Webcam/issues/132#issuecomment-879861332, the title of the issue

**Comment by fangfufu** [comment]
Ah, I got it. I think in both cases it flicks. I am just wondering if thresholding would help. The previous version had thresholding.

**Comment by fangfufu** [comment]
@hp-pepster , I don't feel the two versions are that different.

**Comment by hp-pepster** [comment]
Yes, you are right. But with background_mask_update_speed set to 10 its not flickering but fading, which is less annoying.

I went back to the tf/bodypix version (60307d815d7002f279d2cb53229df29d22e18da7) and no really perfect as well. Maybe my background is too noisy with a lot of books and no homogeneous surface. Tomorrow I will try to put some cloth behind my me and see if that's better.

**Comment by fangfufu** [comment]
bodypix version was just so clunky and slow. I hated it.

**Comment by fangfufu** [comment]
Please check out cbf4f2144b089eb53a14668aebd871aebd26b474
