### ISSUE TITLE
how change the border thresold 

### ISSUE THREAD

**Issue by edefranco** [fangfufu/Linux-Fake-Background-Webcam#135]
For me you recent modifications about the flickering working fine but the image of the body is bleached (but is acceptable).
I have new strange effect only on the head (maybe because I have little hair): there are more border across the head that show the real background.
The rest of the body is ok.
Is possible to change (and regulate) the border across the body?
Emilio

**Comment by fangfufu** [comment]
I haven't programmed that in yet. I have been busy recently. You can turn it off by setting ``--background-mask-update-speed`` to 100.

**Comment by mathieuf20** [comment]
I found out that I had way better results by changing
```
            model_selection=1)
```
to 
```
            model_selection=0)
```
in fake.py at line 147. Google's mediapipe documentation [(here](https://google.github.io/mediapipe/solutions/selfie_segmentation#model_selection) specifies the difference between those 2 values. It is a tiny bit heavier to run on my GPU, but I still manage 30 FPS at 720p on a GTX 1660 SUPER.

**Comment by fangfufu** [comment]
@mathieuf20 , this is interesting. I thought we are running out webcam at landscape, so I selected landscape mode. Also, this software does _not_ use your GPU.

**Comment by edefranco** [comment]
Thanks, for me model_selection= 0 and  background-mask-update-speed=50, is best solution. The result are not as the example on selfie segmentation page, but probably in the example is used GPU ... and I don't use it, I use only CPU.

In any case, I suggest to add in the your readme on the site in the help of fake.py the background-mask-update-speed option ... I think that is fundamental for good use ...

Emilio

**Comment by fangfufu** [comment]
Done in cbf4f2144b089eb53a14668aebd871aebd26b474
