### ISSUE TITLE
npm missing from prerequisities (readme file)

### ISSUE THREAD

**Issue by fransschreuder** [fangfufu/Linux-Fake-Background-Webcam#14]
Hello,
Thanks for this great work of art! I like it and it works really well!
I was just missing npm from the prerequisities in the readme file. It is obvious, but for some people maybe not.

**Comment by fangfufu** [comment]
It says "You need to have Node.js. Node.js version 12 is known to work." in the README.

**Comment by fransschreuder** [comment]
Ok, then I said nothing.
