### ISSUE TITLE
Add config file support

### ISSUE THREAD

**Issue by fangfufu** [fangfufu/Linux-Fake-Background-Webcam#145]
It would be nice if this tool supports configuration file, so we don't have to specify the configuration on command line. I recommend we use the JSON format.

**Comment by snlawrence** [comment]
I can probably take a look at this over the coming week, I've done similar things before.

**Comment by fangfufu** [comment]
Oh, it would be nice if you can make something. I basically put up random ideas as issues. It seems to be a good way to get people's attention and help. :)
