### ISSUE TITLE
Edge TPU support

### ISSUE THREAD

**Issue by mithrandir42** [fangfufu/Linux-Fake-Background-Webcam#147]
Recently added a Google Edge TPU to my system. Since the person detection uses Tensorflow Lite, it should theoretically  be possible to use this thing for inference instead of GPU or CPU.

**Comment by fangfufu** [comment]
Again, you have to recompile everything. 
https://github.com/google/mediapipe/blob/master/mediapipe/examples/coral/README.md
This is outside the scope of this repository.

**Comment by fangfufu** [comment]
Again, if you can somehow magically make the whole process simpler, or if you want to write a tutorial, I am happy to merge them in.

**Comment by mithrandir42** [comment]
For the Edge TPU I still have to find a way to setup the libedgetpu on my gentoo. Anyways curious on testing the TPU. Afterwards I might try it out.  Anyways, having to recompile mediapipe is a good hint.
