### ISSUE TITLE
Expose model_selection as config

### ISSUE THREAD

**Issue by tommyalatalo** [fangfufu/Linux-Fake-Background-Webcam#149]
As mentioned in https://github.com/fangfufu/Linux-Fake-Background-Webcam/issues/135#issuecomment-883361294 the parameter `model_selection` in `fake.py` is set to 1 by default. But having this value as 1 still causes the image mask to flicker a lot, and after trying to switch it over to 0 I also found that the flickering is almost completely removed, the results are far better.

So could this parameter be exposed as a config flag so that we can change it without editing `fake.py` itself?

**Comment by fangfufu** [comment]
Done at 3b09c302e5e64f42ae5be214d86c7aec0c469f0a
