### ISSUE TITLE
Is anyone actually using the Dockerfiles?

### ISSUE THREAD

**Issue by fangfufu** [fangfufu/Linux-Fake-Background-Webcam#151]
If you are using the Dockerfile, please comment below. I am thinking of removing it. I cannot think of the situation in which Python venv would not be enough.

**Comment by mworthley** [comment]
It made much more sense when having the separate js server. I did a lot of work on that docker-compose work and also have stopped using it as the extra overhead (on maintaining) no longer seems worth it.

**Comment by fangfufu** [comment]
I need to do some investigation on Python venv. I think that might be helpful for people who are experiencing stability issues.

**Comment by celvin** [comment]
don't remove it, It makes my life easier! I'm using it a lot.

**Comment by fangfufu** [comment]
@celvin , have you tried Python venv?

**Comment by fangfufu** [comment]
Anyways, I am going to remove Dockerfiles when I next work on this repository, if anyone has objection, please voice them now.

**Comment by tna76874** [comment]
Please do not drop docekr support !
