### ISSUE TITLE
9 FPS while using fake cam

### ISSUE THREAD

**Issue by amamut** [fangfufu/Linux-Fake-Background-Webcam#158]
I get a total of 9 fps using fake-cam. Also the process lists out the consumers every 3 or so seconds which produces a visible stop in the video for half a second.

```
Specs:
CPU: Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz
GPU: Nvidia 980 TI
Camera: Canon Vixia HF G20 (1080P 60fps)

Config file:
width = 1920
height = 1080
fps = 60
webcam-path = /dev/video0
v4l2loopback-path = /dev/video2
background-image = "yacht.jpg"
no-background = no
background-keep-aspect = yes
no-foreground = yes
background-mask-update-speed = 20
```

**Comment by fangfufu** [comment]
Also, you need a better CPU if you are getting 9fps. I am getting 12-14 fps on a i7-4900MQ.

**Comment by fangfufu** [comment]
Hi, please checkout the latest commit (https://github.com/fangfufu/Linux-Fake-Background-Webcam/commit/2f7d6988a3275b8aa4cbc73bed8151666c5aedef), the performance is vastly improved.
