### ISSUE TITLE
device does not exist: /dev/video20

### ISSUE THREAD

**Issue by celvin** [fangfufu/Linux-Fake-Background-Webcam#16]
I'm using the docker setup, and followed the instructions but getting this message:

2020-05-04 22:55:18.833160: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
bodypix_1  | 2020-05-04 22:55:18.833172: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
bodypix_1  | 2020-05-04 22:55:18.833210: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (OptiPlex-9020): /proc/driver/nvidia/version does not exist
fakecam_1  | 
fakecam_1  | --- Make sure the v4l2loopback kernel module is loaded ---
fakecam_1  | sudo modprobe v4l2loopback devices=1
fakecam_1  | 
fakecam_1  | Traceback (most recent call last):
fakecam_1  |   File "fake.py", line 77, in <module>
fakecam_1  |     fake = pyfakewebcam.FakeWebcam('/dev/video20', width, height)
fakecam_1  |   File "/usr/local/lib/python3.8/site-packages/pyfakewebcam/pyfakewebcam.py", line 31, in __init__
fakecam_1  |     raise FileNotFoundError('device does not exist: {}'.format(video_device))
fakecam_1  | FileNotFoundError: device does not exist: /dev/video20

/dev/video2 has 777 permissions

this is the output of v4l2-ctl --list-devices:
v4l2loopback (platform:v4l2loopback-000):
	/dev/video2

HD Pro Webcam C920 (usb-0000:00:14.0-10):
	/dev/video0
	/dev/video1

Notice that I don't have nvidia video card, is that needed?

**Comment by fangfufu** [comment]
I have absolutely no idea what you did. Have you tried updating to the latest version? The Docker version does not depend on CUDA stuff. 

The error message also says:

    FileNotFoundError: device does not exist: /dev/video20

You did not configure your ``docker-compose.yml`` properly.
