### ISSUE TITLE
cv2.error

### ISSUE THREAD

**Issue by takov751** [fangfufu/Linux-Fake-Background-Webcam#20]
self.images["background"] = cv2.resize(background, (self.width, self.height))
fakecam_1  | cv2.error: OpenCV(4.2.0) ../modules/imgproc/src/resize.cpp:4048: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'
fakecam_1  | 
linux-fake-background-webcam_fakecam_1 exited with code 1

It seems that the Opencv 4.2 resize function had been changed

**Comment by fangfufu** [comment]
In that case run the Docker version?

**Comment by takov751** [comment]
This is the docker version I run the docker-compose file with just `docker-compose up`
Before that of course i changed the videodevices to the correct ones

**Comment by fangfufu** [comment]
Can you copy and paste the full log, and indent it properly please? It could just be that you asked your webcam for a mode that is not supported.

**Comment by takov751** [comment]
@fangfufu Asbsolutly my bad i have messed up the webcam location . Thank you for the quick answer i will close this iisue.
