### ISSUE TITLE
No fake.py as mentioned in README.md

### ISSUE THREAD

**Issue by ufechner7** [fangfufu/Linux-Fake-Background-Webcam#206]
The README.md says:
```
When running fake.py, you need to set -v to the first video device that Akvcam created, e.g. if Akvcam created /dev/video5 and /dev/video6, you need to set -v /dev/video5.
```
But I have no file `fake.py`. Where is it supposed to come from?

Using Ubuntu 22.04.

**Comment by fangfufu** [comment]
Somebody decided to rename it to https://github.com/fangfufu/Linux-Fake-Background-Webcam/blob/master/lfbw/lfbw.py
