### ISSUE TITLE
ModuleNotFoundError: No module named 'pyfakewebcam'

### ISSUE THREAD

**Issue by arkantoster** [fangfufu/Linux-Fake-Background-Webcam#21]
Hi, i've had follow the steps, but unfortunatelly by my lack of knowledge i don't know what i did wrong to get this error:

```
$ python3 fake.py
Traceback (most recent call last):
  File "fake.py", line 12, in <module>
    import pyfakewebcam
ModuleNotFoundError: No module named 'pyfakewebcam'
```
 I may be silly, but I really don't know what to do.

**Comment by arkantoster** [comment]
sorry, Can u help me with this problem? why was it closed?

**Comment by fangfufu** [comment]
Hi, you need to use search engine to learn how to install pyfakewebcam and other related module. I don't provide tech support for users who have made zero attempts.

**Comment by fangfufu** [comment]
Hi, you need to use search engine to learn how to install pyfakewebcam and other related software. I don't provide tech support for users who have made zero attempts to do the research themselves.
