### ISSUE TITLE
cant start docker 

### ISSUE THREAD

**Issue by berkiadam** [fangfufu/Linux-Fake-Background-Webcam#24]
I always get the following error: 

no source element for URI "/dev/video0"

I tried to use every possible settings in the docker-compose file. If I list my devices I can see the following list: 

`# v4l2-ctl --list-devices
Vimicro USB Camera (Altair): Vi (usb-0000:00:14.0-1.7):
	/dev/video4
	/dev/video5
	/dev/media2

Integrated_Webcam_HD: Integrate (usb-0000:00:14.0-6):
	/dev/video0
	/dev/video1
	/dev/video2
	/dev/video3
	/dev/media0
	/dev/media1`

I want to use the Vimicro USB Camera. According to the list above what would be the proper device setting in the compose file? 

   devices:
            # input (webcam)
            - /dev/video4:/dev/video4
            # output (virtual webcam)
            - /dev/video5:/dev/video6

Can you please give me some instructions? 

Thanks
Adam

**Comment by fangfufu** [comment]
Please refer to 
https://docs.docker.com/compose/compose-file/#devices

It probably should be 

            # input (webcam)
            - /dev/video4:/dev/video0
            # output (virtual webcam)
            - /dev/video2:/dev/video6

assuming your v4l2loopback device is /dev/video6
