### ISSUE TITLE
It's running slower out of the blue.

### ISSUE THREAD

**Issue by rizzini** [fangfufu/Linux-Fake-Background-Webcam#28]
I noticed since just this morning that Linux-Fake-Background-Webcam is running a bit slower with some delay. Like I said on [reddit](https://www.reddit.com/r/linux/comments/gmspno/my_fake_webcam_project_now_supports_animated/fr5y62a/?context=3), it was running flawlessly. My node and python3 CPU consumption was around 13% combined. Now it's around 35%.

Proof: https://www.youtube.com/watch?v=DkyoLct74tg&feature=youtu.be

I have no idea how to troubleshoot Node JS, though I saw something different running `node app.js `.

Before: `I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions: AVX2 FMA`

Now: `I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA`

I don't remember doing nothing different from before to now.

**Comment by fangfufu** [comment]
Where did you get your old copy of nodejs from? I _need_ to know. Do you do a lot of web development? Do you have a powerful GPU?

**Comment by rizzini** [comment]
> Where did you get your old copy of nodejs from? 
Anywhere. I didn't even have npm installed before this. This is what is bugging me.. To have extra CPU instructions, I need to build my own TensorFlow. I'm missing something here. I even tought that my terminal from my YouTube video was cutting some letters, but, even so, you can see that's not it. The message it is indeed different.

> Do you do a lot of web development?
Not at all.


> Do you have a powerful GPU?
Nope. It's an Intel iGPU. Intel(R) HD Graphics 4600.

**Comment by fangfufu** [comment]
Do you use Tensorflow at all? By the sound of it, it might have been using the Tensorflow binary from elsewhere.

**Comment by rizzini** [comment]
Yeah. It sound like that. Until I figure this out, I'll keep this issue closed, since it's appears to be my mistake.

**Comment by fangfufu** [comment]
Do let me know if you manage to figure it out. I really can't be bothered to compile my own tensorflow.

**Comment by fangfufu** [comment]
@rizzini , I wrote an instruction on how to compile Tensorflow C library. If you want to gain performance, please follow that. 
https://github.com/fangfufu/Linux-Fake-Background-Webcam/blob/master/TENSORFLOW.md

**Comment by rizzini** [comment]
You're awesome! I'll definitely gonna do it later today. Thank you. =)

**Comment by fangfufu** [comment]
I don't know if it actually makes that much difference, it gave me like 1 FPS increase or something, The FPS changed from 11.5 FPS to 12.5FPS. But then again somehow the v4l2 reports my real webcam can only do 10 FPS. The compilation takes nearly 2 hours, btw.
