### ISSUE TITLE
Error running node

### ISSUE THREAD

**Issue by jrpenaneto** [fangfufu/Linux-Fake-Background-Webcam#34]
Hi!
I'm getting the following error when running node:

$ node app.js
internal/modules/cjs/loader.js:638
    throw err;
    ^
Error: Cannot find module '@tensorflow/tfjs-node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/jose/Linux-Fake-Background-Webcam-master/bodypix/app.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

Info on system:
[code]

System:    Host: mx Kernel: 4.19.0-6-amd64 x86_64 bits: 64 compiler: gcc v: 8.3.0 
           parameters: BOOT_IMAGE=/boot/vmlinuz-4.19.0-6-amd64 
           root=UUID=39ae572a-7ca5-480b-add7-387526f94788 ro quiet splash 
           Desktop: Xfce 4.14.2 tk: Gtk 3.24.5 info: xfce4-panel wm: xfwm4 dm: LightDM 1.26.0 
           Distro: MX-19.1_x64 patito feo February 15  2020 base: Debian GNU/Linux 10 (buster) 
Machine:   Type: Laptop System: LENOVO product: VILG1 v: Lenovo G400s serial: <filter> Chassis: 
           type: 10 v: Lenovo G400s serial: <filter> 
           Mobo: LENOVO model: INVALID v: K0E50515STD serial: <filter> UEFI: LENOVO 
           v: 7BCN38WW(V2.04) date: 12/10/2013 
Battery:   ID-1: BAT1 charge: 15.2 Wh condition: 25.6/37.6 Wh (68%) volts: 14.9/14.4 
           model: LENOVO PABAS0241231 type: Li-ion serial: <filter> status: Unknown 
CPU:       Topology: Dual Core model: Intel Core i5-3230M bits: 64 type: MT MCP arch: Ivy Bridge 
           family: 6 model-id: 3A (58) stepping: 9 microcode: 21 L2 cache: 3072 KiB 
           flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 20752 
           Speed: 3020 MHz min/max: 1200/3200 MHz Core speeds (MHz): 1: 2994 2: 3007 3: 2993 
           4: 2993 
           Vulnerabilities: Type: itlb_multihit status: KVM: Split huge pages 
           Type: l1tf mitigation: PTE Inversion; VMX: conditional cache flushes, SMT vulnerable 
           Type: mds mitigation: Clear CPU buffers; SMT vulnerable 
           Type: meltdown mitigation: PTI 
           Type: spec_store_bypass 
           mitigation: Speculative Store Bypass disabled via prctl and seccomp 
           Type: spectre_v1 mitigation: usercopy/swapgs barriers and __user pointer sanitization 
           Type: spectre_v2 mitigation: Full generic retpoline, IBPB: conditional, IBRS_FW, 
           STIBP: conditional, RSB filling 
           Type: tsx_async_abort status: Not affected 
Graphics:  Device-1: Intel 3rd Gen Core processor Graphics vendor: Lenovo driver: i915 v: kernel 
           bus ID: 00:02.0 chip ID: 8086:0166 
           Display: x11 server: X.Org 1.20.4 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1366x768~60Hz, 1280x720~60Hz 
           OpenGL: renderer: Mesa DRI Intel Ivybridge Mobile v: 4.2 Mesa 18.3.6 compat-v: 3.0 
           direct render: Yes 
Audio:     Device-1: Intel 7 Series/C216 Family High Definition Audio vendor: Lenovo 
           driver: snd_hda_intel v: kernel bus ID: 00:1b.0 chip ID: 8086:1e20 
           Sound Server: ALSA v: k4.19.0-6-amd64 
Network:   Device-1: Qualcomm Atheros AR8162 Fast Ethernet vendor: Lenovo driver: alx v: kernel 
           port: 2000 bus ID: 01:00.0 chip ID: 1969:1090 
           IF: eth0 state: up speed: 100 Mbps duplex: full mac: <filter> 
           Device-2: Qualcomm Atheros AR9485 Wireless Network Adapter vendor: Lenovo 
           driver: ath9k v: kernel port: 2000 bus ID: 02:00.0 chip ID: 168c:0032 
           IF: wlan0 state: down mac: <filter> 
Drives:    Local Storage: total: 931.51 GiB used: 230.56 GiB (24.8%) 
           ID-1: /dev/sda vendor: Seagate model: ST1000LM024 HN-M101MBB size: 931.51 GiB 
           block size: physical: 4096 B logical: 512 B speed: 6.0 Gb/s rotation: 5400 rpm 
           serial: <filter> rev: 0001 temp: 30 C scheme: GPT 
Partition: ID-1: / raw size: 423.55 GiB size: 415.90 GiB (98.19%) used: 79.11 GiB (19.0%) 
           fs: ext4 dev: /dev/sda10 
           ID-2: swap-1 size: 3.90 GiB used: 0 KiB (0.0%) fs: swap swappiness: 15 (default 60) 
           cache pressure: 100 (default) dev: /dev/sda9 
Sensors:   System Temperatures: cpu: 63.0 C mobo: N/A 
           Fan Speeds (RPM): N/A 
Repos:     No active apt repos in: /etc/apt/sources.list 
           No active apt repos in: /etc/apt/sources.list.d/d-apt.list 
           Active apt repos in: /etc/apt/sources.list.d/debian-stable-updates.list 
           1: deb http://deb.debian.org/debian/ buster-updates main contrib non-free
           Active apt repos in: /etc/apt/sources.list.d/debian.list 
           1: deb http://deb.debian.org/debian/ buster main contrib non-free
           2: deb http://deb.debian.org/debian-security/ buster/updates main contrib non-free
           3: deb http://deb.debian.org/debian/ buster-backports main contrib non-free
           Active apt repos in: /etc/apt/sources.list.d/dropbox.list 
           1: deb [arch=i386,amd64] http://linux.dropbox.com/debian/ buster main
           Active apt repos in: /etc/apt/sources.list.d/google-chrome.list 
           1: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
           Active apt repos in: /etc/apt/sources.list.d/megasync.list 
           1: deb https://mega.nz/linux/MEGAsync/Debian_10.0/ ./
           Active apt repos in: /etc/apt/sources.list.d/mx.list 
           1: deb https://mxlinux.c3sl.ufpr.br/mx-workspace/mx/repo/ buster main non-free
           Active apt repos in: /etc/apt/sources.list.d/skype-stable.list 
           1: deb [arch=amd64] https://repo.skype.com/deb/ stable main
           Active apt repos in: /etc/apt/sources.list.d/spotify.list 
           1: deb http://repository.spotify.com/ stable non-free
           No active apt repos in: /etc/apt/sources.list.d/various.list 
Info:      Processes: 233 Uptime: 22m Memory: 3.75 GiB used: 1.69 GiB (45.0%) Init: SysVinit 
           v: 2.93 runlevel: 5 default: 5 Compilers: gcc: 8.3.0 alt: 8 Shell: bash v: 5.0.3 
           running in: quick-system-in inxi: 3.0.36 
[/code]

Thanks.

**Comment by fangfufu** [comment]
You haven't install tensorflowjs properly.
