### ISSUE TITLE
Invalid signature during installation of OpenCV dependencies

### ISSUE THREAD

**Issue by RTM13** [fangfufu/Linux-Fake-Background-Webcam#4]
The build process returns an error when trying to install the packages listed in the .fakecam/Dockerfile
starting at line 5. 

    Step 1/9 : FROM python:3
    3: Pulling from library/python
    Digest: sha256:3df040cc8e804b731a9e98c82e2bc5cf3c979d78288c28df4f54bbdc18dbb521
    Status: Downloaded newer image for python:3
    ---> b55669b4130e
    Step 2/9 : RUN pip install --upgrade pip
    ---> Using cache
    ---> 422cb4859c68
    Step 3/9 : RUN apt-get update &&   apt-get install -y   `# opencv requirements`   libsm6 libxext6 libxrender-dev   `# opencv video opening requirements`   libv4l-dev
    ---> Running in 9d3af7efff8d
    Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
    Get:2 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
    Get:3 http://deb.debian.org/debian buster-updates InRelease [49.3 kB]
    Err:2 http://security.debian.org/debian-security buster/updates InRelease
    At least one invalid signature was encountered.
    Err:1 http://deb.debian.org/debian buster InRelease
    At least one invalid signature was encountered.
    Err:3 http://deb.debian.org/debian buster-updates InRelease
    At least one invalid signature was encountered.
    Reading package lists...
    W: GPG error: http://security.debian.org/debian-security buster/updates InRelease: At least one invalid signature was encountered.
    E: The repository 'http://security.debian.org/debian-security buster/updates InRelease' is not signed.
    W: GPG error: http://deb.debian.org/debian buster InRelease: At least one invalid signature was encountered.
    E: The repository 'http://deb.debian.org/debian buster InRelease' is not signed.
    W: GPG error: http://deb.debian.org/debian buster-updates InRelease: At least one invalid signature was encountered.
    E: The repository 'http://deb.debian.org/debian buster-updates InRelease' is not signed.
    The command '/bin/sh -c apt-get update &&   apt-get install -y   `# opencv requirements`   libsm6 libxext6 libxrender-dev   `# opencv video opening requirements`   libv4l-dev' returned a non-zero code: 100

Any suggestions how to fix this?

**Comment by fangfufu** [comment]
Delete the intermediate images and try again? Looks like Debian package's signatures are out of date. It might be a transient problem.
