### ISSUE TITLE
Sentence in the README just ends

### ISSUE THREAD

**Issue by anoadragon453** [fangfufu/Linux-Fake-Background-Webcam#42]
> If you already have already configured akvcam via webcamoid, you need to modify the

Modify the what? :)

**Comment by fangfufu** [comment]
You need to modify the ``/etc/akvcam/config.ini`` to add the ``rw`` attributes. Proofreading is not my strong point. lol.

**Comment by anoadragon453** [comment]
Ftr this was fixed by https://github.com/fangfufu/Linux-Fake-Background-Webcam/commit/762ac8a7a2454e790109eb5e2afa052babc46f6f

Thanks!

**Comment by fangfufu** [comment]
No worries, thanks for spotting the mistake! 

By the way, I see that you work on Matrix / Vector project, that is really cool!

**Comment by anoadragon453** [comment]
@fangfufu Thank you! Yes, I think so too :)
