### ISSUE TITLE
Performance issues on docker CPU builds

### ISSUE THREAD

**Issue by gmontamat** [fangfufu/Linux-Fake-Background-Webcam#46]
Hi, I've been using Linux-Fake-Background-Webcam with docker-compose for a while and noticed a huge performance drop since 05ed29fedc695718528e5ababf402a973db6bd01. I'm using a .mov video background and no foreground. Any docker builds since that commit run at less than 1fps.
Steps I use to build older but faster version:
```
git checkout -b old-release 05ed29fedc695718528e5ababf402a973db6bd01
# edit docker-compose.yml as needed
docker-compose up --build
```
I'm running Ubuntu 18.04 with kernel 5.4.0-42-generic on an Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz

**Comment by fangfufu** [comment]
Have you tried a non-Docker version?
