### ISSUE TITLE
AMD GPU

### ISSUE THREAD

**Issue by 1552937** [fangfufu/Linux-Fake-Background-Webcam#48]
Is there a way to get this working with and gpus and maybe even AMD integrated gpus?

**Comment by fangfufu** [comment]
You can try and compile it against OpenCL. I think AMD GPUs use that API. 
https://github.com/fangfufu/Linux-Fake-Background-Webcam/blob/master/TENSORFLOW.md

**Comment by 1552937** [comment]
You were right. I thought for months it just didn't work with opencl but now I understand-I screwed up my drivers. Now I use cuda for this stuff.
