### ISSUE TITLE
How to select source video feed

### ISSUE THREAD

**Issue by p-phillips** [fangfufu/Linux-Fake-Background-Webcam#51]
Hi.

Managed to get the code installed and working but I can only use the default laptop camera, not the second USB webcam I usually use on an external monitor.

Is this configured in the v4l2loopback module options ? I know I need to make it use /dev/video1 as the input stream rather than /dev/video0 but it is not clear to me how I do that.

Pete

**Comment by fangfufu** [comment]
The readme literally says:

    -w WEBCAM_PATH, --webcam-path WEBCAM_PATH
                        Set real webcam path

**Comment by p-phillips** [comment]
Doh.  I was convinced it would be the module.  
Thank you.
