### ISSUE TITLE
OSError: [Errno 22] Invalid argument, not fixed by using latest v4l2loopback built from source

### ISSUE THREAD

**Issue by WhyDoWeWonder** [fangfufu/Linux-Fake-Background-Webcam#55]
Attempting to run `python fake.py` results in 
https://pastebin.com/XWSCLJuF

I'm using Arch Linux with kernel 5.8.5-arch1-1, I've tried using the v4l2loopback-dkms aur package, v4l2loopback-dkms-git aur package, and cloning then building from [source](https://github.com/umlaeute/v4l2loopback). I've also tried using akvcam which has resulted in the following error.
https://pastebin.com/fmzgtjDN

I've restarted my computer every time I installed and uninstall v4l2loopback.

**Comment by oldmud0** [comment]
How did you fix this?

**Comment by WhyDoWeWonder** [comment]
I passed in the arguments for the input and output video devices manually. If that doesn't work, edit the python files and hardcode the video /dev/videoX devices.
