### ISSUE TITLE
HSV color removal

### ISSUE THREAD

**Issue by christf** [fangfufu/Linux-Fake-Background-Webcam#58]
fangfufu, thank you for this collection of tools and for putting in the effort to iterate over the original blogpost.
This has worked for me immediately.

Unfortunately using bodypix gives me 2-3 frames per second on my core m5 cpu, so I prepared another iteration on top of your code on https://github.com/christf/fakebackground. This uses color removal via hsv key.

The effects are similar to the bodypix approach and yield a 11-15 FPS performance on my CPU, yet requires a green cloth for the background.

It could be interesting to work on the wobbling and to improve on the image processing - maybe using bodypix every second or two to re-assess the hsv values from the background and then do the more efficient background calculation for realtime processing of the data.

Anyways - I just wanted to say hi and thank you

Cheers
christf

**Comment by christf** [comment]
I reduced wobbling by applying a sliding average across 3 masks and using that as final mask. If you are interested, I'd be happy to raise this and the green screen background removal as PR.

**Comment by fangfufu** [comment]
Sorry I had been away, due to house moving, new job and PhD viva. 

I don't want the green screen background removal, as other tools can already do that. 

I am intetered in the wobbling reduction code though.

**Comment by fangfufu** [comment]
Please check out the latest commit. I am using Mediapipe as the backend. It is so much faster now.
