### ISSUE TITLE
Can the software be made work offline?

### ISSUE THREAD

**Issue by lesshaste** [fangfufu/Linux-Fake-Background-Webcam#59]
If I have recorded video (mp4 say), can a virtual background be added to it using this software?

**Comment by oliv3r** [comment]
@lesshaste what makes you think it wouldn't? :) It works fine offline :p

**Comment by lesshaste** [comment]
That's great! Could you show how you would feed in an MP4 file for example?

**Comment by oliv3r** [comment]
Well anything that [OpenCV's VideoCapture](https://docs.opencv.org/3.4/d8/dfe/classcv_1_1VideoCapture.html) supports really as can be seen here: https://github.com/fangfufu/Linux-Fake-Background-Webcam/blob/master/fakecam/fake.py#L188

The file-filter takes as argument a background file, or you just name it background.<whatever> as can be seen here
https://github.com/fangfufu/Linux-Fake-Background-Webcam/blob/master/fakecam/fake.py#L330

I haven't tried it on mp4 but works fine on gif's, where it's named background.gif

**Comment by fangfufu** [comment]
It does support video background. I have tried it before.
