### ISSUE TITLE
Port 9000

### ISSUE THREAD

**Issue by mf-1** [fangfufu/Linux-Fake-Background-Webcam#71]
I'm using Docker portainer.io with port 9000.

In this case I cannot use LFBW at port 9000, too. Even I have to stop portainer.io.

Using `export PORT=9011` I can see with `netstat -l | grep 9011`that somebody will hear at this port. But I get no video from my fakecam device. Even port 9000 is free or not.

Using a local path I habe the same effect.

Any other suggestions?

**Comment by turnopil** [comment]
Try to expose the `BPPORT` variable instead of `PORT`
https://github.com/fangfufu/Linux-Fake-Background-Webcam/blob/master/bodypix/app.js#L6

**Comment by mf-1** [comment]
@turnopil Thx for your information but this wasn't working...

```
user@computer:/opt/Linux-Fake-Background-Webcam$ export BPPORT=9011 && node /opt/Linux-Fake-Background-Webcam/bodypix/app.js &
[1] 1483219
user@computer:/opt/Linux-Fake-Background-Webcam$ No GPU found at /dev/nvidia0, using CPU
2020-11-25 15:46:38.173987: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3203165000 Hz
2020-11-25 15:46:38.174291: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3211c70 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-11-25 15:46:38.174315: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version

user@computer:/opt/Linux-Fake-Background-Webcam$ 
user@computer:/opt/Linux-Fake-Background-Webcam$ netstat -l | grep 9000
tcp6       0      0 [::]:9000               [::]:*                  LISTEN     
user@computer:/opt/Linux-Fake-Background-Webcam$ netstat -l | grep 9011
user@computer:/opt/Linux-Fake-Background-Webcam$ 
user@computer:/opt/Linux-Fake-Background-Webcam$ echo $BPPORT
9011
user@computer:/opt/Linux-Fake-Background-Webcam$ 
```

Since some days I've moved portainer to port 8000 which shouldn't be the case ...

Any other suggestions?

**Comment by fangfufu** [comment]
This is no longer relevant, as I am using Mediapipe as the backend.
