### ISSUE TITLE
add a foreground image

### ISSUE THREAD

**Issue by liske** [fangfufu/Linux-Fake-Background-Webcam#8]
After you have updated the background image I think we also need a foreground image. The foreground image needs to support alpha channel (.png?) and could be used to get the illusion of a speaker's desk. What did you think?

**Comment by fangfufu** [comment]
This is an excellent idea. Do you plan to submit a pull request? Or should I do it?

**Comment by fangfufu** [comment]
fixed in 661776b5d8eba9dd0be49b9fc39b607b99e4cc24

Please check if it works for you, especially under Docker. it works for me.

**Comment by liske** [comment]
I was playing around with opencv while being offline, but your implementation is somewhat more flexible.

It is working perfectly, the foreground files are just missing in the Dockerfile (see #9).

**Comment by fangfufu** [comment]
That's great. :) 

What's the opencv approach? What did you mean by this approach is more flexible? This approach uses OpenCV as well. It just uses an external mask generator for background segmentation.

**Comment by liske** [comment]
> That's great. :)
> 
> What's the opencv approach? What did you mean by this approach is more flexible?

This is my first time getting in touch with OpenCV. My implementation 425be92eb028689053f296d1472f7f00fe6d5f56 did only add a foreground mask. Your approach is IMHO more flexible using a dedicated foreground and background image.

**Comment by fangfufu** [comment]
Ah, I see. I thought about doing it your way, but then I thought people might want to add random things into the foreground. 

How did you locate that particular commit in the log anyway? I can't seem to find it. 

I did notice something when I merged your pull request, but I suppose I wasn't paying enough attention.

**Comment by liske** [comment]
> How did you locate that particular commit in the log anyway? I can't seem to find it.

I did just put the commit id into the reply and it seems to somehow find it in the branch at my repository ;-)

**Comment by fangfufu** [comment]
Github's commit history view isn't showing it. I meant I can access the commit you linked as well, but I can't see it in Github's commit listing. Oh wells. I am just wondering how your changes managed to merge with my changes, because we modified the same file at the same time. Somehow your changes got discarded.

**Comment by liske** [comment]
Nope, I did not create a pull request. This it the umerged branch: https://github.com/liske/Linux-Fake-Background-Webcam/tree/add-foreground

**Comment by fangfufu** [comment]
Ahh I see. Thanks!
