### ISSUE TITLE
Cannot create container for service bodypix: Unknown runtime specified nvidia

### ISSUE THREAD

**Issue by RobinSchapendonk** [fangfufu/Linux-Fake-Background-Webcam#85]
```
Creating linux-fake-background-webcam_bodypix_1 ... error

ERROR: for linux-fake-background-webcam_bodypix_1  Cannot create container for service bodypix: Unknown runtime specified nvidia

ERROR: for bodypix  Cannot create container for service bodypix: Unknown runtime specified nvidia
ERROR: Encountered errors while bringing up the project.
```

If using NVIDIA version, docker-compose 1.27.0+ needed to allow for runtime option in file format v3.
```
docker-compose -v
docker-compose version 1.28.3, build unknown
```

Note: I use optimus-manager hybrid mode, because I have an integrated and a nvidia gpu in my laptop.

**Comment by fangfufu** [comment]
Does CUDA work normally on your machine? What does CUDA-Z report? (http://cuda-z.sourceforge.net/)

**Comment by RobinSchapendonk** [comment]
(sorry for late response) tbh I don't know. The laptop now is gone anyway so I can't check it......

**Comment by grazzolini** [comment]
I have this exact same issue. I'm using Arch Linux and I do have CUDA setup on the host, but when I try to build with the nvidia docker compose file, it doesn't work. I does work with the regular one though.

**Comment by grazzolini** [comment]
Ok, so I was missing the nvidia-container-runtime
