### ISSUE TITLE
Fake.py python file error

### ISSUE THREAD

**Issue by Sanchit112** [fangfufu/Linux-Fake-Background-Webcam#91]
![Screenshot from 2021-04-02 21-08-40](https://user-images.githubusercontent.com/35194828/113430400-bfdbf280-93f7-11eb-8d6e-5f6f8998b55e.png)

**Comment by ChristianMoll** [comment]
I'm getting exactly the same error after following the readme instructions.

**Comment by Sanchit112** [comment]
Disable secure boot from bios that worked for me, but still unable to make its thing work. Getting an error: cannot connect to port 9000
