### ISSUE TITLE
suggestions for out of the box installation

### ISSUE THREAD

**Issue by mwiesweg** [fangfufu/Linux-Fake-Background-Webcam#95]
With the configuration out of the box, installation failed miserably with cryptic errors.
Two suggestions:
- I needed to install "gyp" whatever that is. "pip install git+https://chromium.googlesource.com/external/gyp" worked for this
- I needed to modify the version specification in bodypix/package.json changing the caret "^" to a ">=". With this, npm install runs cleanly.
- akvcam really seems to be the working option on ubuntu. Neither zoom nor Cheese recognize the v4l2loopback device. Please add to the docs that you have to specify the fake.py command line "--akvcam -v /dev/videoX" where X is the number of the first of two devices provided by the driver (akvcam (out))

**Comment by samhh** [comment]
For what it's worth I've got the v4l2 method working fine with Zoom on Arch.

**Comment by fangfufu** [comment]
v4l2 is certain dodgy, but akvcam sometimes crashes. @mwiesweg , feel free to submit a pull request.

**Comment by fangfufu** [comment]
This is no longer relevant, as I am using Mediapipe as the backend. Please check out the latest commit.
